### ISSUE TITLE
[严重]（管理门户）系统管理-新建系统用户，不赋权限，直接登录。应允许登录，能看到主页面

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-MGMT-SYS#10]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chenhy9  密码：123456
步骤：
1.系统管理-新建系统用户，不赋权限，直接登录。
实际结果：提示用户所属主角色不存在
预期结果：允许登录，能看到主页面

**Comment by mapl-pisces** [comment]
新建用户必须赋权限角色才可以登录，另外主页面也是一个模块，需要配置权限

**Comment by chenhy6** [comment]
通过
