### ISSUE TITLE
【严重】（管理门户）系统管理-后台权限-系统角色，没有进行角色资源分配，不应显示在 用户角色分配 的分配角色列表中

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-MGMT-SYS#11]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.系统管理-后台权限-系统角色-添加角色后，角色 没有进行角色资源分配
实际结果：
显示在 用户角色分配 的分配角色列表中
预期结果：
不应显示在 用户角色分配 的分配角色列表中

**Comment by renfeng3** [comment]
@chenhy6 经讨论 暂不改

**Comment by chenhy6** [comment]
通过
