### ISSUE TITLE
[致命]（管理门户）系统管理-后台权限-系统角色，将平台管理员 改为：无效后，所有管理员都登不进系统，提示 此用户没有主角色存在

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-MGMT-SYS#12]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.系统管理-后台权限-系统角色，将平台管理员 改为：无效
实际结果：
所有管理员都登不进系统，提示 此用户没有主角色存在。
预期结果：能否做下限制，平台管理员不让修改

**Comment by mapl-pisces** [comment]
重新构建系统管理子系统paas-csys，修改内容：点击平台管理员角色是不再弹出管理窗口，不能改变角色代码，角色名称，有效状态等；其他角色保持不变

**Comment by chenhy6** [comment]
问题解决，验证通过
