### ISSUE TITLE
[一般]（管理门户）系统管理-后台权限-角色资源分配，分配了根角色，没有分配根角色下的子角色。再给系统用户分配此用户角色，登录时 报500（没有权限）

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-MGMT-SYS#13]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.系统管理-后台权限-角色资源分配，分配了根角色，没有分配根角色下的子角色。再给系统用户分配此用户角色
实际结果：
登录时 报500（没有权限）
预期结果：可以登录系统，看到此根菜单。

**Comment by chenhy6** [comment]
验证通过

**Comment by mapl-pisces** [comment]
1）、提测的功能说明：在没有子菜单时，非叶子结点不会刷新整个页面
2）、代码分支说明：https://github.com/AIPaaS/PaaS-FE-WEB.git  develop
        https://github.com/AIPaaS/PaaS-FE-MGMT-Web.git    develop
3）、配置信息说明：无
4）、数据库说明：无
5）、是否有特殊的第三方软件安装：无

**Comment by chenhy6** [comment]
验证通过
