### ISSUE TITLE
[一般]（管理门户）登录-系统管理-前台/后台权限-用户添加/修改功能，保存后，弹窗能否做成自动关闭（建议）

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-MGMT-SYS#15]
环境：win7
浏览器：IE9
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.进入 系统管理-前台/后台权限-用户添加/修改功能，保存后，弹窗不会自动关闭（建议）
实际结果：
点击“保存”后，不会自动关闭
预期结果：
保存后，弹窗做成自动关闭（建议）

**Comment by mapl-pisces** [comment]
确认不用修改，关闭
