### ISSUE TITLE
【一般】（管理门户）登录-资源管理-资源中心部署-列表-服务器编号，预期结果：不允许编辑

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-MGMT-SYS#19]
环境：win7
浏览器：火狐
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.进入 资源管理-资源中心部署-列表-服务器编号
实际结果：允许编辑
预期结果：不允许编辑

**Comment by yuanman001** [comment]
此处为服务器信息的超链接，跳转到服务器编辑页面，故可允许编辑。

**Comment by chenhy6** [comment]
通过
