### ISSUE TITLE
[一般]（管理门户）租户管理-租户注册审批-申请状态-查询-下拉框-列表 显示全部信息的选项，显示空白，建议：添上“全部“

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-MGMT-SYS#4]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.租户管理-租户注册审批-申请状态-查询-下拉框-列表 显示全部信息的选项
实际结果：
显示全部信息的选项，显示空白
预期结果：
建议：添上“全部“字样
 备注：资源配额审批、版本库开通 有同样问题

**Comment by haoyh1** [comment]
这个问题只是改了页面效果，真正改正确需要改整个框架改需要问领导，因为有些地方 空和全部是两个不同的状态。

**Comment by haoyh1** [comment]
@chenhy6 这个问题只是改了页面效果，真正改正确需要改整个框架改需要问领导，因为有些地方 空和全部是两个不同的状态。

**Comment by haoyh1** [comment]
@chenhy6 这个问题只是改了页面效果，真正改正确需要改整个框架改需要问领导，因为有些地方 空和全部是两个不同的状态。

**Comment by chenhy6** [comment]
不做修改

**Comment by chenhy6** [comment]
通过
