### ISSUE TITLE
[一般]（管理门户）系统管理-前台权限-前台角色-添加/修改-角色代码/角色名称项，输入无限大字符时，点击“保存”按钮，报错

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-MGMT-SYS#7]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.系统管理-前台权限-前台角色-添加/修改-角色代码/角色名称项，输入无限大字符时，点击“保存”按钮，报错“call remote service 'sysrolesvc.saveorupdate()'error!ora-12899:value too large for colum”"paas_sys"."sys_role"."role_code"(actual:48,maximum:40);
建议：在页面上做字符输入限制

**Comment by chenhy6** [comment]
问题没解决

**Comment by chenhy6** [comment]
问题没解决

**Comment by chenhy6** [comment]
问题没解决

**Comment by chenhy6** [comment]
问题没解决

**Comment by haoyh1** [comment]
@chenhy6  构建后生效。 限制为40个字符，不要问我为什么是40。谁会把角色代码介绍名称输的无限大。

**Comment by chenhy6** [comment]
验证通过
