### ISSUE TITLE
【严重】（管理门户）系统管理-前/后台权限-系统/用户角色，设置为无效时，用户角色分配-分配角色列表，不应显示此无效的角色

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-MGMT-SYS#8]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.系统管理-前/后台权限-系统/用户角色，设置为无效时，用户角色分配-分配角色列表，不应显示此无效的角色
备注：用户角色有相同问题

**Comment by renfeng3** [comment]
@chenhy6 以修复

**Comment by chenhy6** [comment]
通过
